This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./memoria.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file memoria.acn...
!! Input index error (file = memoria.acn, line = 1):
   -- Illegal space within numerals in second argument.
.done (47 entries accepted, 1 rejected).
Sorting entries....done (265 comparisons).
Generating output file memoria.acr....done (55 lines written, 0 warnings).
Output written in memoria.acr.
Transcript written in memoria.alg.
